### PR TITLE
ci: run type checking earlier

### PR DESCRIPTION
**Pull request by mstruebing**
# Description

As `dist` is running anyway, which runs `tsc`, which includes a type
check and we need to run `dist` before or rather
`predist`/`build:design-tokens` before we are able to run `test:types`
I decided to remove the `test:types` check from CI.

## Testing

Produce a type error and run `npm run dist` locally.

## Checklist

- [ ] This PR is associated with a JIRA and it is mentioned in the commit message footer ("Closes …")
- [ ] Significant changes have been tested downstream to avoid breaking changes
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [ ] I have reviewed the changes and provided detail to the sections above

### CODE REVIEW

**Comment by clintonmedbery** [comment]
I am unsure, but it looks like we might have to run this after dist?

**Comment by nataliepina** [comment]
> I am unsure, but it looks like we might have to run this after dist?

Judging by this error `Cannot find module '../../../packages/design-tokens/build/js/designTokens' or its corresponding type declarations.` we would need `npm run dist` to happen first.

**Comment by mstruebing** [comment]
Remove the type check completly.

**Review by nataliepina — APPROVED** [review]

**Comment by clintonmedbery** [comment]
Nice!

**Review by clintonmedbery — APPROVED** [review]

**Pull request merged**
