### PR TITLE
build: dependabot configuration

### PR DESCRIPTION
**Pull request by nataliepina**
These changes add a config file for dependabot.
Dependabot helps to create routine dependency updates.

# Description

This introduces depnedabot for UI Kit! 

## Testing
Merging this will trigger the dependabot updates. 

## Checklist

- [ ] This PR is associated with a JIRA and it is mentioned in the commit message footer ("Closes …")
- [ ] Significant changes have been tested downstream to avoid breaking changes
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [x] I have reviewed the changes and provided detail to the sections above

### CODE REVIEW

**Comment by nataliepina** [comment]
> https://github.com/mesosphere/kommander/blob/main/.github/dependabot.yml

DKP insights team set them to 10 so I based it off of that but less. I will definitely introduce the day of the week here and I will up this but I don't know about 50 that seems excessive for no reason? 🤔

**Comment by mstruebing** [comment]
Here is an example of the approve and merge automation: https://github.com/mesosphere/kommander/blob/main/.github/workflows/dependabot-automations.yaml

We do not need to introduce this in this PR, this can be a separate one.

**Review by clintonmedbery — APPROVED** [review]
Best way to find out if this works is to get it in.

**Review by mstruebing — APPROVED** [review]

**Comment by mstruebing** [comment]
@nataliepina Please get this automation into `kommander-ui` as well 🙏

**Pull request merged**
