### PR TITLE
feat: new border radius design tokens

### PR DESCRIPTION
**Pull request by nataliepina**
New border radius for round borders.

BREAKING CHANGE:
Previously the default border radius was set to 6px, now it is set to 4px. Previously the small border radius was set to 4px, now it is set to 2px.

Closes D2IQ-95453

# Description

#### The Problem
There is inconsistent use of border-radius throughout UI Kit. There was not any information, standards, or guidelines to inform these inconsistencies. 

We are following an 8px grid system. 4px will align better with that system so the design team and myself have opted to update the default to that value.

I found several locations where the border radius was set to be completely round but used different values. Due to the amount of these, it seemed fit to create a new design token to address the inconsistencies. This semantic token better describes the style applied compared to "999px" or "50%". 

I wrote some additional information to share about rounded corners and consistency that I will include below. 

<hr>

#### Benefits of Rounded Corners

We are conditioned for rounded corners. Think of sharp objects and the connotations of danger. Think about what “baby-proofing” a house entails. Rounded corners communicate safety and can make us feel more at ease. So believe it or not, there is some psychology behind setting a border-radius throughout the application. There is a level of the subconscious mind that is active when we interact with the UI. We may not have the same threats as we did when we were cave people, though our brains are still trained to be on the lookout for perceived threats.

Rounded corners give off a modern appearance. They have become a design trend in the last couple of years, but there is some thought and information to support why that is.

Having rounded corners makes the UI easier for our eyes to process. They are great to use to appeal to the eye as a kind of psychological comfort.

They also make for effective content containers. Since the corners point inward, this places more focus on the content as your eyes are naturally drawn inward.

There are a few exceptions to rounded edges and situations where a sharp edge without a border-radius set might be preferred. Sharper edges do tend to express serious and professional feelings about an interface. It can give clean, aligned, and serious. 

There is a space between sharp and round that is a great middle ground. It is common to encounter a 4px radius to achieve this. It expresses more of a friendly and accommodating vibe than a sharp edge at 0px. 

There is a slew of other reasons and nuances to all of this, but ultimately it’s important to be consistent with the rounding of edges to align with the subtle details you want to communicate. It can impact users' thoughts overall of the product.

#### Benefits of Consistency

You’ve probably heard me say “for consistency” a million times by now. It’s an important and huge part of UI design!
Humans love consistency and expected behaviors when interacting with a user interface. Usability and learnability improve when elements have a consistent visual appearance and function. 
When you have consistency in the design, users can more easily transfer knowledge to new contexts and learn quickly. This allows users to focus on executing tasks and not on learning how to use the product itself. 
Consistency eliminates confusion. Consistency saves money and time for users! 

##### Resources
https://uxdesign.cc/design-principle-consistency-6b0cf7e7339f
https://uxplanet.org/rounded-or-sharp-corner-buttons-def3977ed7c4

## Trade-offs
Sidenote, discovered that I cannot update the style-dictionary created table in the border-radius documentation. There is a bug that I logged for this. 

## Checklist

- [x] This PR is associated with a JIRA and it is mentioned in the commit message footer ("Closes …")
- [ ] Significant changes have been tested downstream to avoid breaking changes
- [x] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [x] I have reviewed the changes and provided detail to the sections above

### CODE REVIEW

**Review by seialkali — CHANGES_REQUESTED** [review]
Looks good overall! Do you ever foresee us using `borderRadiusSmall` for anything?

Also, this will need to be updated with the new values: https://github.com/d2iq/ui-kit/blob/381119aee57819828be6be5ba42203ab9257e4cf/design-guidelines/design-tokens/layout.md?plain=1#L62-L63

**Comment by nataliepina** [comment]
> Looks good overall! Do you ever foresee us using `borderRadiusSmall` for anything?
> 
> Also, this will need to be updated with the new values:
> 
> https://github.com/d2iq/ui-kit/blob/381119aee57819828be6be5ba42203ab9257e4cf/design-guidelines/design-tokens/layout.md?plain=1#L62-L63

I could see us using `borderRadiusSmall` in the future. I didn't want to remove this token because if someone was using it by chance it will only change the size and not cause them any errors from it missing.

We cannot update the design tokens table yet, unfortunately. There is an error with our style dictionary that I discovered while working on this. I logged it under [this JIRA](https://d2iq.atlassian.net/browse/D2IQ-95943) and brought it into the next sprint. It's only for our documentation purposes so I don't see it as a blocker for these changes.

**Review by seialkali — APPROVED** [review]

**Comment by seialkali** [comment]
> We cannot update the design tokens table yet, unfortunately. There is an error with our style dictionary that I discovered while working on this. I logged it under [this JIRA](https://d2iq.atlassian.net/browse/D2IQ-95943) and brought it into the next sprint. It's only for our documentation purposes so I don't see it as a blocker for these changes.

Sorry, I've only just seen your note in the trade offs section now!

**Comment by nataliepina** [comment]
> > We cannot update the design tokens table yet, unfortunately. There is an error with our style dictionary that I discovered while working on this. I logged it under [this JIRA](https://d2iq.atlassian.net/browse/D2IQ-95943) and brought it into the next sprint. It's only for our documentation purposes so I don't see it as a blocker for these changes.
> 
> Sorry, I've only just seen your note in the trade offs section now!

No worries, I forgot to add that bit so I went back and included it! Thanks for reminding me :)

**Review by mstruebing — APPROVED** [review]
It's weird in what way the tests are failing, it doesn't really look like it should be related to your changes.

**Pull request merged**
