### PR TITLE
feat: dependencies will use version ranges

### PR DESCRIPTION
**Pull request by nataliepina**
Version ranges are preferred over fixed versioning for libraries.

Closes D2IQ-98697

# Description
Shout out to @mstruebing for the idea to move away from fixed versioning to version ranges since this is a library. 

Version ranges are preferred over fixed versioning for libraries because they allow for flexibility and adaptability by permitting updates within a specified major version, ensuring compatibility while receiving bug fixes and new features without requiring manual adjustments to dependencies.

## Which issue(s) does this PR relate to?

 - https://jira.d2iq.com/browse/D2IQ-98697

## Testing
A regression test should do. 
It will be great to test this downstream as well with an updated version next. 

## Screenshots
I'd like to use this section to call out a UI Kit win! 

Just 3 months ago we were at `34 (including 10 moderate, 23 high, and 1 critical)` 
3monthsago-fixed

Over the last few months I have been updating all of the dependencies, along with help from the open source community.
This reduced that down to 2 moderate vulnerabilities.  
current-fixed

As of these changes today we are officially at 0 vulnerabilities 🎉 
next

Reducing vulnerabilities in software dependencies is vital to ensure security, stability, and user trust. Vulnerable dependencies can lead to data breaches, cyberattacks, and system failures, undermining the integrity of user data and disrupting service. By actively addressing vulnerabilities, software teams safeguard against potential threats, comply with regulations, minimize reactive maintenance, and demonstrate a commitment to long-term software viability. This proactive approach not only enhances software performance but also fosters collaborative trust within the development community.

## Checklist

- [x] This PR is associated with a JIRA and it is mentioned in the commit message footer ("Closes …")
- [ ] Significant changes have been tested downstream to avoid breaking changes
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [x] I have reviewed the changes and provided detail to the sections above

### CODE REVIEW

**Comment by vacas5** [comment]
Would this be considered a breaking change?

**Comment by nataliepina** [comment]
> Would this be considered a breaking change?

I was not quite sure that it would be a breaking change. Nothing will break within DKP UI though it may be considering a breaking change for others depending on the configuration of their project. I've included that in the commit message now to be on the safe side.

**Review by mstruebing — APPROVED** [review]
🎉 

I'm not quite sure about the breaking change, when we make changes to other dependencies we most notably don't even treat it as a feature. (except peer dependencies).

**Review by clintonmedbery — APPROVED** [review]
Thanks!!!

**Pull request merged**
