### PR TITLE
chore: rename old dcos things

### PR DESCRIPTION
**Pull request by vacas5**
Update to reflect the repo org move.

# Description

## Checklist

- [ ] This PR is associated with a JIRA and it is mentioned in the commit message footer ("Closes …")
- [ ] Significant changes have been tested downstream to avoid breaking changes
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [ ] I have reviewed the changes and provided detail to the sections above

### CODE REVIEW

**Comment by nataliepina** [comment]
Will we have to wait to update the name ` "name": "@dcos/ui-kit"?

And this related section of the documentation:
`Run the following in the host project:

`npm link @dcos/ui-kit`

After running the command above, restart the host application.

Note: Do not run `npm install` again or you will override changes.
`

**Comment by vacas5** [comment]
see updated @nataliepina

**Review by mstruebing — COMMENTED** [review]
The package is still named `@dcos/ui-kit` - do we want to move it to a d2iq organisation?
Seems like we have one: https://www.npmjs.com/package/@d2iq/dsl-filter

**Comment by nataliepina** [comment]
> The package is still named `@dcos/ui-kit` - do we want to move it to a d2iq organisation? Seems like we have one: https://www.npmjs.com/package/@d2iq/dsl-filter

Yeah this is my question as well but we may have to do that as a follow-up until we can figure out how to get access to the org on npm.

**Review by nataliepina — APPROVED** [review]
Approved! Feel free to include the package name changes in here if we can figure that out or if it should be separated but nothing to hold this back for me.

**Comment by vacas5** [comment]
oh, yes, sorry. I'll have to figure out how we start publishing to a different org in npm. It's a totally different deal

**Pull request merged**
