### PR TITLE
Kavandalal/refactor/radioinput story

### PR DESCRIPTION
**Pull request by kavandalal**
# Description

## Which issue(s) does this PR relate to?

https://github.com/d2iq/ui-kit/issues/1000

## Screenshots

image

## Checklist

- [ ] This PR is associated with a JIRA and it is mentioned in the commit message footer ("Closes …")
- [ ] Significant changes have been tested downstream to avoid breaking changes
- [ ] This PR contains breaking changes and states in the commit message body ("BREAKING CHANGE: …")
- [ ] I have reviewed the changes and provided detail to the sections above

### CODE REVIEW

**Comment by clintonmedbery** [comment]
This looks good! You could clean up that extra commit but running `git reset --soft HEAD~1` to reset the commit where you deleted the comment and then running `git commit --amend` to add the clean up to the previous commit.

**Review by nataliepina — APPROVED** [review]
This looks great, thank you @kavandalal. Congrats on your first contribution to UI Kit.

If you wouldn't mind following Clinton's suggestion to clean up the extra commit, after that we can merge this in.

Cheers!

**Comment by nataliepina** [comment]
Looks like there are now 4 commits here now, could you amend them please so that it becomes 1 commit for `refactor: RadioInput component story code`.

**Comment by kavandalal** [comment]
Sorry @nataliepina, I am facing some issue with git, not able to perform execution as expected !!

**Comment by kavandalal** [comment]
It took time for me to understand the problem, But now its 1 commit

**Comment by nataliepina** [comment]
No problem, thank you for adjusting it, merging this!

**Pull request merged**
